### ISSUE TITLE
JBoss Problem

### ISSUE THREAD

**Issue by jgabrielcabral** [dojot/docker-compose#57]
Hello, i started one vm today with 2048MB RAM with Ubuntu 16.04, and installed Dojot realease 0.2.0 - Aikido platform from Docker Compose. In the log of running process, this showed the next message, its like a JBOSS problem: 

```
=========================================================================
alarm-manager_1         |
alarm-manager_1         |   JBoss Bootstrap Environment
alarm-manager_1         |
alarm-manager_1         |   JBOSS_HOME: /opt/jboss/wildfly
alarm-manager_1         |
alarm-manager_1         |   JAVA: /usr/lib/jvm/java/bin/java
alarm-manager_1         |
alarm-manager_1         |   JAVA_OPTS:  -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
alarm-manager_1         |
alarm-manager_1         | 
=========================================================================
alarm-manager_1         |
alarm-manager_1         | 06:19:21,214 INFO  [org.jboss.modules] (main) JBoss Modules version 1.5.1.Final
alarm-manager_1         | 06:19:21,911 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.6.Final
alarm-manager_1         | 06:19:22,151 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) starting
alarm-manager_1         | 06:19:24,354 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
alarm-manager_1         |       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:131) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.as.server.ServerService.boot(ServerService.java:356) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:299) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at java.lang.Thread.run(Thread.java:748) [rt.jar:1.8.0_161]
alarm-manager_1         | Caused by: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[39,5]
alarm-manager_1         | Message: WFLYCTL0198: Unexpected element '{urn:jboss:domain:4.0}system-properties' encountered
alarm-manager_1         |       at org.jboss.as.controller.parsing.ParseUtils.unexpectedElement(ParseUtils.java:89) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.as.server.parsing.StandaloneXml_4.readServerElement(StandaloneXml_4.java:268) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.as.server.parsing.StandaloneXml_4.readElement(StandaloneXml_4.java:141) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:103) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:49) [wildfly-server-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:110) [staxmapper-1.2.0.Final.jar:1.2.0.Final]
alarm-manager_1         |       at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:69) [staxmapper-1.2.0.Final.jar:1.2.0.Final]
alarm-manager_1         |       at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:123) [wildfly-controller-2.0.10.Final.jar:2.0.10.Final]
alarm-manager_1         |       ... 3 more
alarm-manager_1         |
alarm-manager_1         | 06:19:24,364 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
alarm-manager_1         | 06:19:24,372 INFO  [org.jboss.as.server] (Thread-2) WFLYSRV0220: Server shutdown has been requested.
alarm-manager_1         | 06:19:24,407 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0050: WildFly Full 10.0.0.Final (WildFly Core 2.0.10.Final) stopped in 19ms
alarm-manager_1         | 
=========================================================================
```

This is normal? Have a solution or is a issue?

**Comment by danielnunesdeoliveira** [comment]
Hi @jgabrielcabral 

I advice you follow this specification:
![image](https://user-images.githubusercontent.com/29581014/49241536-3cf19a00-f3ef-11e8-96e8-3b42905b5b5a.png)

**Comment by rascaraficci** [comment]
We don't support the alarm-manager anymore. I recommend you to use a newer version of dojot platform.

**Comment by rascaraficci** [comment]
This issue will be closed due to inactivity
